name: Python application

on:
  schedule:
    - cron: "0 10 * * 1,3,6" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install requests;
    - name: Update prices
      run: |
        python main.py > "./latest-prices.txt";
    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Update latest prices.'
